name = "discord-oidc"
main = "src/workers.ts"
compatibility_date = "2023-08-01"

kv_namespaces = [
  { binding = "KV", id = "0b9abda82acf461c8d4ecda656217e20", preview_id = "b43c22430b5240dea89cd6cc350d3946" }
]

[triggers]
crons = ["0 */1 * * *"]

[vars]
DISCORD_CLIENT_ID="YOUR_CLIENT_ID"
REDIRECT_URL="https://YOURNAME.cloudflareaccess.com/cdn-cgi/access/callback"
SERVERS_ROLE_CLAIMS=["YOUR_SERVER_ID"]
CACHE_ROLES=true
